version: '3'

services:
  app:
    build: .
    ports:
      - "3001:3000"
    environment:
      - MONGODB_URI=mongodb://localhost:27017/stockInvestment
    volumes:
      - ./:/app
    restart: always
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
