version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/stockInvestment
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - mongo
    networks:
      - stock-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - stock-network

networks:
  stock-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
